### PR TITLE
Use postgresql 15

### PR DESCRIPTION
**Pull request by sayan3296**
* Switch from rhel8 to rhel9 and postgresql 15
* Remove leading spaces

### CODE REVIEW

**Comment by sayan3296** [comment]
CC @takaelucky

**Comment by waldirio** [comment]
hey,

Thank you @sayan3296 !!!

@takaelucky , please, let me know if you can review/test it.

Thank you, friends!
Waldirio

**Comment by sayan3296** [comment]
JFYI, The podman pull attempts may fail due to ongoing issues with security scanning [ as reported in status.redhat.com ]

So 10+ retries are needed to get one pull successful just once.

**Comment by takaelucky** [comment]
LGTM

**Comment by waldirio** [comment]
@sayan3296 and @takaelucky 

Thank you!!! teamwork++
Waldirio

**Pull request merged**
